site_name: RazorKit
site_author: Emrah KONDUR
repo_name: ekondur/RazorKit
repo_url: https://github.com/ekondur/RazorKit
theme:
    name: material
    icon:
        repo: fontawesome/brands/git-alt
    features:
        - content.code.copy
        - content.code.select
        - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - DataTables: 
    - Get Started: datatables/index.md
  - ChartJs: 
    - Get Started: chartjs/index.md
    - Chart Types: chartjs/types.md
    - Options: chartjs/options.md
    - Plugins: chartjs/plugins.md
    - Scales: chartjs/scales.md
    - Elements: chartjs/elements.md
    - Layout: chartjs/layout.md
    - Animation: chartjs/animation.md
    - Interaction: chartjs/interaction.md