site_name: RazorKit
site_url: https://ekondur.github.io/RazorKit/
site_author: Emrah KONDUR
site_description: RazorKit is a collection of lightweight, fluent-style Razor HTML helpers that make it easy for developers to integrate popular JavaScript libraries into their ASP.NET applications. With RazorKit, you can quickly implement features from libraries like Chart.js and DataTables, without the hassle of writing complex JavaScript or HTML code manually.
repo_name: ekondur/RazorKit
repo_url: https://github.com/ekondur/RazorKit
theme:
    name: material
    logo: rk-logo-m.png
    favicon: rk-icon.png
    icon:
        repo: fontawesome/brands/git-alt
    features:
        - content.code.copy
        - content.code.select
        - content.code.annotate
        - content.tooltips
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - search.share
        - search.suggest
markdown_extensions:
    - def_list
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - pymdownx.tabbed:
        alternate_style: true
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - toc:
        permalink: true
extra:
  analytics:
    provider: google
    property: G-SNHZZKGMSL
nav:
  - Home: index.md
  - DataTables: 
    - DataTables: datatables/index.md
    - Options: datatables/options.md
    - Columns: datatables/columns.md
    - DataSource: datatables/datasource.md
    - Callbacks: datatables/callbacks.md
    - Command: datatables/command.md
    - Command Group: datatables/command-group.md
    - Language: datatables/language.md
    - Filters: datatables/filters.md
    - Layout: datatables/layout.md
    - Extensions:
        - AutoFill: datatables/extensions/autofill.md
        - Buttons: datatables/extensions/buttons.md
        - ColReorder: datatables/extensions/colreorder.md
        - FixedColumns: datatables/extensions/fixedcolumns.md
        - FixedHeader: datatables/extensions/fixedheader.md
        - KeyTable: datatables/extensions/keytable.md
        - Responsive: datatables/extensions/responsive.md
        - RowGroup: datatables/extensions/rowgroup.md
        - RowReorder: datatables/extensions/rowreorder.md
        - Select: datatables/extensions/select.md
  - ChartJs: 
    - ChartJs: chartjs/index.md
    - Configuration: chartjs/configuration.md
    - Chart Types:
        - Bar Chart: chartjs/datasets/bar.md
        - Bubble Chart: chartjs/datasets/bubble.md
        - Doughnut and Pie Charts: chartjs/datasets/doughnut-pie.md
        - Line Chart: chartjs/datasets/line.md
        - Mixed Chart Types: chartjs/datasets/mixed.md
        - Polar Area Chart: chartjs/datasets/polar-area.md
        - Radar Chart: chartjs/datasets/radar.md
        - Scatter Chart: chartjs/datasets/scatter.md
    - Plugins:
        - Title: chartjs/plugins/title.md
        - Subtitle: chartjs/plugins/subtitle.md
        - Legend: chartjs/plugins/legend.md
        - Tooltip: chartjs/plugins/tooltip.md
        - Collors: chartjs/plugins/collors.md
        - Decimation: chartjs/plugins/decimation.md
        - Filler: chartjs/plugins/filler.md
    - Elements:
        - Arc: chartjs/elements/arc.md
        - Bar: chartjs/elements/bar.md
        - Line: chartjs/elements/line.md
        - Point: chartjs/elements/point.md
    - Axes: 
        - Scales: chartjs/axes/scales.md
        - Grid: chartjs/axes/grid.md
        - Ticks: chartjs/axes/ticks.md
        - Title: chartjs/axes/title.md
        - Callbacks: chartjs/axes/callbacks.md
        - Border: chartjs/axes/border.md
    - Other Options:
        - Layout: chartjs/layout.md
        - Animation: chartjs/animation.md
        - Interaction: chartjs/interaction.md
        - Padding: chartjs/padding.md
        - Font: chartjs/font.md
  - SweetAlert2: 
    - SweetAlert2: sweetalert2/index.md
    - Configuration: sweetalert2/configuration.md
    - General Options: sweetalert2/general.md
    - Button Options: sweetalert2/button.md
    - Functions: sweetalert2/functions.md
    - Custom Class: sweetalert2/custom-class.md